DROP TABLE IF EXISTS requests;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS bookings;
DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT generated by default as identity NOT NULL,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    constraint pk_user PRIMARY KEY (id),
    constraint UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT generated by default as identity NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    is_available BOOLEAN NOT NULL,
    owner_id BIGINT NOT NULL references users(id),
    request_id BIGINT,
    constraint pk_items PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT generated by default as identity NOT NULL,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    item_id BIGINT NOT NULL REFERENCES items(id),
    booker_id BIGINT not null REFERENCES users(id),
    status VARCHAR(20) NOT NULL ,
    constraint pk_bookings PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description varchar(255) NOT NULL,
    requestor_id BIGINT NOT NULL REFERENCES users(id),
    constraint pk_requests PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text varchar(255) NOT NULL,
    item_id BIGINT NOT NULL REFERENCES items(id),
    author_id BIGINT NOT NULL REFERENCES users(id),
    created TIMESTAMP NOT NULL,
    constraint pk_comments PRIMARY KEY (id)
);