CREATE TABLE IF NOT EXISTS users (
    id BIGINT generated by default as identity NOT NULL,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL,
    constraint pk_user PRIMARY KEY (id),
    constraint UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT generated by default as identity NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    available BOOLEAN NOT NULL,
    owner_id BIGINT NOT NULL references users(id),
    constraint pk_items PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT generated by default as identity NOT NULL,
    creator_id BIGINT not null references users(id),
    state VARCHAR(20) NOT NULL ,
    creation_date TIMESTAMP NOT NULL,
    constraint pk_bookings PRIMARY KEY (id)
);